/**
 * NOUFAL Advanced Scheduling System - React Components
 * نظام NOUFAL المتقدم للجدولة الزمنية
 * 
 * Includes:
 * - Smart Schedule Generator from BOQ
 * - Advanced Schedule Viewer with CPM
 * - S-Curve Visualization
 * - Export/Import functionality
 */

import React, { useState, useMemo } from 'react';
import { 
    FinancialItem, 
    AdvancedScheduleTrendingUp as Activity, 
    WBSItem,
    CPMAnalysisResult,
    SCurveData 
} from '../types';
import { ActivityAnalyzer } from '../intelligence/ActivityAnalyzer';
import { CPMEngine } from '../intelligence/CPMEngine';
import { SBCCompliance } from '../intelligence/SBCCompliance';
import { 
    SCurveGenerator, 
    ScheduleExportService, 
    ScheduleImportService 
} from '../services/ScheduleServices';
import { ExcelExporter } from '../services/ExcelExporter';
import { GanttChartViewer } from './GanttChartViewer';
import { 
    Calendar, 
    Download, 
    Upload, 
    TrendingUp, 
    AlertTriangle, 
    CheckCircle,
    FileText,
    BarChart3
} from 'lucide-react';

// ==================== Smart Schedule Generator Component ====================

interface SmartScheduleGeneratorProps {
    boqItems: FinancialItem[];
    onScheduleGenerated: (activities: AdvancedScheduleActivity[], wbs: WBSItem[]) => void;
}

export const SmartScheduleGenerator: React.FC<SmartScheduleGeneratorProps> = ({
    boqItems,
    onScheduleGenerated
}) => {
    const [isGenerating, setIsGenerating] = useState(false);
    const [projectStartDate, setProjectStartDate] = useState(new Date().toISOString().split('T')[0]);
    const [generationStatus, setGenerationStatus] = useState<string>('');

    const handleGenerateSchedule = async () => {
        setIsGenerating(true);
        setGenerationStatus('جاري تحليل بنود المقايسة...');

        try {
            // Step 1: Analyze and breakdown BOQ items
            const analyzer = new ActivityAnalyzer();
            const breakdowns = analyzer.analyzeAndBreakdown(boqItems);
            setGenerationStatus(`تم تحليل ${breakdowns.length} بند - جاري إنشاء الأنشطة...`);

            // Step 2: Extract all activities
            const activities = breakdowns.flatMap(b => b.activities);
            setGenerationStatus(`تم إنشاء ${activities.length} نشاط - جاري فحص الكود السعودي...`);

            // Step 3: Apply SBC Compliance
            SBCCompliance.applyComplianceAdjustments(activities);
            setGenerationStatus('تم التحقق من متطلبات الكود السعودي - جاري إنشاء العلاقات...');

            // Step 4: Auto-generate dependencies
            CPMEngine.autoGenerateDependencies(activities);
            setGenerationStatus('تم إنشاء العلاقات - جاري حساب المسار الحرج...');

            // Step 5: Perform CPM analysis
            const cpmResult = CPMEngine.performCPM(activities, new Date(projectStartDate));
            setGenerationStatus('تم حساب المسار الحرج - جاري بناء WBS...');

            // Step 6: Build WBS structure
            const wbs = analyzer.buildWBS(breakdowns);
            setGenerationStatus('تم بناء هيكل WBS - اكتمل التوليد!');

            // Callback with results
            onScheduleGenerated(activities, wbs);

            setTimeout(() => setGenerationStatus(''), 3000);
        } catch (error: any) {
            setGenerationStatus(`خطأ: ${error.message}`);
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <div className="bg-white dark:bg-slate-900/50 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800">
            <div className="flex items-center mb-4">
                <Calendar className="w-5 h-5 ml-2" />
                <h2 className="text-xl font-semibold">مولد الجدول الزمني الذكي - NOUFAL</h2>
            </div>

            <div className="space-y-4">
                <div>
                    <label className="block text-sm font-medium mb-2">تاريخ بدء المشروع</label>
                    <input 
                        type="date"
                        value={projectStartDate}
                        onChange={(e) => setProjectStartDate(e.target.value)}
                        className="w-full p-2 border rounded-lg dark:bg-slate-800 dark:border-slate-700"
                    />
                </div>

                <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg">
                    <h4 className="font-semibold mb-2 flex items-center">
                        <CheckCircle className="w-4 h-4 ml-2" />
                        ميزات النظام
                    </h4>
                    <ul className="text-sm space-y-1 mr-4">
                        <li>✓ تفكيك بنود المقايسة إلى أنشطة تفصيلية (WBS)</li>
                        <li>✓ حساب المدد بناءً على معدلات إنتاجية سعودية</li>
                        <li>✓ التحقق من الكود السعودي (SBC 301, 304, 306, 308, 403)</li>
                        <li>✓ إنشاء العلاقات التلقائية بين الأنشطة</li>
                        <li>✓ حساب المسار الحرج (CPM)</li>
                        <li>✓ حساب Float للأنشطة</li>
                    </ul>
                </div>

                {generationStatus && (
                    <div className="p-3 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300 rounded-lg">
                        {generationStatus}
                    </div>
                )}

                <button
                    onClick={handleGenerateSchedule}
                    disabled={isGenerating || boqItems.length === 0}
                    className="w-full bg-indigo-600 text-white py-3 px-4 rounded-lg hover:bg-indigo-700 disabled:bg-gray-400 font-semibold flex items-center justify-center"
                >
                    {isGenerating ? (
                        <>جاري التوليد...</>
                    ) : (
                        <>
                            <TrendingUp className="w-5 h-5 ml-2" />
                            توليد الجدول الزمني من المقايسة
                        </>
                    )}
                </button>
            </div>
        </div>
    );
};

// ==================== Advanced Schedule Viewer Component ====================

interface AdvancedScheduleViewerProps {
    activities: AdvancedScheduleActivity[];
    wbs: WBSItem[];
    projectName: string;
}

export const AdvancedScheduleViewer: React.FC<AdvancedScheduleViewerProps> = ({
    activities,
    wbs,
    projectName
}) => {
    const [activeView, setActiveView] = useState<'activities' | 'wbs' | 'critical' | 'scurve' | 'compliance' | 'gantt'>('activities');
    const [selectedActivity, setSelectedActivity] = useState<AdvancedScheduleActivity | null>(null);

    // Calculate CPM analysis
    const cpmAnalysis = useMemo(() => {
        if (activities.length === 0) return null;
        const projectStart = new Date(Math.min(...activities.map(a => new Date(a.startDate).getTime())));
        return CPMEngine.performCPM(activities, projectStart);
    }, [activities]);

    // Generate S-Curve data
    const sCurveData = useMemo(() => {
        if (activities.length === 0) return [];
        const projectStart = new Date(Math.min(...activities.map(a => new Date(a.startDate).getTime())));
        const projectEnd = new Date(Math.max(...activities.map(a => new Date(a.endDate).getTime())));
        return SCurveGenerator.generateSCurve(activities, projectStart, projectEnd);
    }, [activities]);

    // Get SBC compliance report
    const complianceReport = useMemo(() => {
        return SBCCompliance.generateComplianceReport(activities);
    }, [activities]);

    // Calculate project dates for Gantt chart
    const projectDates = useMemo(() => {
        if (activities.length === 0) return { start: new Date(), end: new Date() };
        const start = new Date(Math.min(...activities.map(a => new Date(a.startDate).getTime())));
        const end = new Date(Math.max(...activities.map(a => new Date(a.endDate).getTime())));
        return { start, end };
    }, [activities]);

    // Export handlers
    const handleExportExcel = () => {
        // Use new professional Excel exporter
        ExcelExporter.exportSchedule(activities, projectName, {
            includeResources: true,
            includeProjectInfo: true
        });
    };

    const handleExportPrimavera = () => {
        ScheduleExportService.exportToPrimavera(activities, projectName);
    };

    const handlePrintPDF = () => {
        ScheduleExportService.printPDF(activities, projectName);
    };

    if (activities.length === 0) {
        return (
            <div className="bg-white dark:bg-slate-900/50 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 text-center">
                <p className="text-gray-500">لا توجد أنشطة في الجدول الزمني. قم بتوليد الجدول أولاً.</p>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            {/* Header with Export Options */}
            <div className="bg-white dark:bg-slate-900/50 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800">
                <div className="flex justify-between items-center mb-4">
                    <h2 className="text-2xl font-bold">عارض الجدول الزمني المتقدم</h2>
                    <div className="flex gap-2">
                        <button
                            onClick={handleExportExcel}
                            className="flex items-center gap-2 bg-green-600 text-white py-2 px-4 rounded-lg hover:bg-green-700"
                        >
                            <Download className="w-4 h-4" /> Excel
                        </button>
                        <button
                            onClick={handleExportPrimavera}
                            className="flex items-center gap-2 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700"
                        >
                            <Download className="w-4 h-4" /> Primavera
                        </button>
                        <button
                            onClick={handlePrintPDF}
                            className="flex items-center gap-2 bg-red-600 text-white py-2 px-4 rounded-lg hover:bg-red-700"
                        >
                            <FileText className="w-4 h-4" /> PDF
                        </button>
                    </div>
                </div>

                {/* Project Summary */}
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                    <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                        <p className="text-sm text-gray-600 dark:text-gray-400">إجمالي الأنشطة</p>
                        <p className="text-2xl font-bold text-blue-600">{activities.length}</p>
                    </div>
                    <div className="p-4 bg-red-50 dark:bg-red-900/20 rounded-lg">
                        <p className="text-sm text-gray-600 dark:text-gray-400">الأنشطة الحرجة</p>
                        <p className="text-2xl font-bold text-red-600">
                            {activities.filter(a => a.isCritical).length}
                        </p>
                    </div>
                    <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-lg">
                        <p className="text-sm text-gray-600 dark:text-gray-400">مدة المشروع</p>
                        <p className="text-2xl font-bold text-green-600">
                            {cpmAnalysis?.projectDuration || 0} يوم
                        </p>
                    </div>
                    <div className="p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
                        <p className="text-sm text-gray-600 dark:text-gray-400">الامتثال للكود</p>
                        <p className="text-2xl font-bold text-purple-600">
                            {complianceReport.compliancePercentage.toFixed(1)}%
                        </p>
                    </div>
                </div>
            </div>

            {/* View Tabs */}
            <div className="bg-white dark:bg-slate-900/50 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800">
                <div className="flex gap-2 border-b border-gray-200 dark:border-gray-700 p-4">
                    {[
                        { key: 'activities', label: 'الأنشطة' },
                        { key: 'wbs', label: 'WBS' },
                        { key: 'critical', label: 'المسار الحرج' },
                        { key: 'gantt', label: 'مخطط جانت' },
                        { key: 'scurve', label: 'منحنى S' },
                        { key: 'compliance', label: 'الامتثال SBC' }
                    ].map(tab => (
                        <button
                            key={tab.key}
                            onClick={() => setActiveView(tab.key as any)}
                            className={`px-4 py-2 rounded-lg font-semibold ${
                                activeView === tab.key
                                    ? 'bg-indigo-600 text-white'
                                    : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300'
                            }`}
                        >
                            {tab.label}
                        </button>
                    ))}
                </div>

                <div className="p-6">
                    {/* Activities View */}
                    {activeView === 'activities' && (
                        <div className="overflow-x-auto">
                            <table className="min-w-full text-right">
                                <thead className="bg-slate-50 dark:bg-slate-800">
                                    <tr>
                                        {['ID', 'WBS', 'النشاط', 'المدة', 'البدء', 'الانتهاء', 'Float', 'حرج'].map(h => (
                                            <th key={h} className="p-3 text-sm font-medium">{h}</th>
                                        ))}
                                    </tr>
                                </thead>
                                <tbody>
                                    {activities.map(act => (
                                        <tr 
                                            key={act.id}
                                            className={`border-b hover:bg-slate-50 dark:hover:bg-slate-800/50 cursor-pointer ${
                                                act.isCritical ? 'bg-red-50 dark:bg-red-900/20' : ''
                                            }`}
                                            onClick={() => setSelectedActivity(act)}
                                        >
                                            <td className="p-2">{act.id}</td>
                                            <td className="p-2 text-xs">{act.wbsCode}</td>
                                            <td className="p-2 font-medium">{act.name}</td>
                                            <td className="p-2">{act.duration} يوم</td>
                                            <td className="p-2 text-sm">{act.startDate}</td>
                                            <td className="p-2 text-sm">{act.endDate}</td>
                                            <td className="p-2">{act.totalFloat}</td>
                                            <td className="p-2 text-center">
                                                {act.isCritical && <span className="text-red-600">★</span>}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}

                    {/* WBS View */}
                    {activeView === 'wbs' && (
                        <div className="space-y-3">
                            {wbs.map(item => (
                                <div key={item.code} className="border rounded-lg p-4">
                                    <div className="flex justify-between items-center">
                                        <h4 className="font-bold">{item.name}</h4>
                                        <span className="text-sm text-gray-500">{item.code}</span>
                                    </div>
                                    <div className="grid grid-cols-3 gap-4 mt-2 text-sm">
                                        <div>
                                            <span className="text-gray-600">الأنشطة:</span>
                                            <span className="font-semibold mr-2">{item.activities.length}</span>
                                        </div>
                                        <div>
                                            <span className="text-gray-600">المدة:</span>
                                            <span className="font-semibold mr-2">{item.totalDuration} يوم</span>
                                        </div>
                                        <div>
                                            <span className="text-gray-600">التكلفة:</span>
                                            <span className="font-semibold mr-2">{item.totalCost.toLocaleString()} ريال</span>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}

                    {/* Critical Path View */}
                    {activeView === 'critical' && (
                        <div>
                            <h3 className="font-bold text-lg mb-4 text-red-600">المسار الحرج - Critical Path</h3>
                            <div className="space-y-2">
                                {activities.filter(a => a.isCritical).map(act => (
                                    <div key={act.id} className="border-l-4 border-red-500 p-4 bg-red-50 dark:bg-red-900/20 rounded">
                                        <div className="flex justify-between">
                                            <span className="font-semibold">{act.name}</span>
                                            <span className="text-sm">{act.duration} يوم</span>
                                        </div>
                                        <div className="text-sm text-gray-600 mt-1">
                                            {act.startDate} → {act.endDate}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Gantt Chart View */}
                    {activeView === 'gantt' && (
                        <GanttChartViewer
                            activities={activities}
                            projectName={projectName}
                            projectStart={projectDates.start}
                            projectEnd={projectDates.end}
                        />
                    )}

                    {/* S-Curve View */}
                    {activeView === 'scurve' && (
                        <div>
                            <h3 className="font-bold text-lg mb-4">منحنى S - Progress Tracking</h3>
                            <p className="text-gray-600 mb-4">
                                نقاط البيانات: {sCurveData.length} | 
                                التقدم المخطط: {sCurveData[sCurveData.length - 1]?.plannedProgress.toFixed(1)}%
                            </p>
                            <div className="bg-gray-50 dark:bg-gray-800 p-4 rounded-lg">
                                <p className="text-center text-gray-500">
                                    تصور منحنى S (يتطلب مكتبة Recharts للعرض الكامل)
                                </p>
                            </div>
                        </div>
                    )}

                    {/* SBC Compliance View */}
                    {activeView === 'compliance' && (
                        <div>
                            <h3 className="font-bold text-lg mb-4">تقرير الامتثال للكود السعودي</h3>
                            <div className="grid grid-cols-2 gap-4 mb-6">
                                <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-lg">
                                    <p className="text-sm">أنشطة ممتثلة</p>
                                    <p className="text-2xl font-bold text-green-600">
                                        {complianceReport.compliantActivities}
                                    </p>
                                </div>
                                <div className="p-4 bg-red-50 dark:bg-red-900/20 rounded-lg">
                                    <p className="text-sm">انتهاكات</p>
                                    <p className="text-2xl font-bold text-red-600">
                                        {complianceReport.nonCompliantActivities}
                                    </p>
                                </div>
                            </div>

                            {complianceReport.violations.length > 0 && (
                                <div className="space-y-3">
                                    <h4 className="font-semibold text-red-600 flex items-center">
                                        <AlertTriangle className="w-4 h-4 ml-2" />
                                        الانتهاكات المطلوب معالجتها
                                    </h4>
                                    {complianceReport.violations.map(v => (
                                        <div key={v.activityId} className="border-l-4 border-red-500 p-4 bg-red-50 dark:bg-red-900/20 rounded">
                                            <p className="font-semibold">{v.activityName}</p>
                                            <ul className="text-sm mt-2 space-y-1">
                                                {v.violations.map((viol, idx) => (
                                                    <li key={idx} className="text-red-700 dark:text-red-300">
                                                        • {viol.code}: {viol.complianceNotes}
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            </div>

            {/* Activity Details Modal */}
            {selectedActivity && (
                <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" onClick={() => setSelectedActivity(null)}>
                    <div className="bg-white dark:bg-slate-900 p-6 rounded-xl max-w-2xl w-full max-h-[80vh] overflow-y-auto" onClick={(e) => e.stopPropagation()}>
                        <h3 className="text-xl font-bold mb-4">{selectedActivity.name}</h3>
                        
                        <div className="grid grid-cols-2 gap-4 text-sm">
                            <div><strong>WBS:</strong> {selectedActivity.wbsCode}</div>
                            <div><strong>المدة:</strong> {selectedActivity.duration} يوم</div>
                            <div><strong>البدء المبكر:</strong> {selectedActivity.earlyStart}</div>
                            <div><strong>الانتهاء المبكر:</strong> {selectedActivity.earlyFinish}</div>
                            <div><strong>البدء المتأخر:</strong> {selectedActivity.lateStart}</div>
                            <div><strong>الانتهاء المتأخر:</strong> {selectedActivity.lateFinish}</div>
                            <div><strong>Float الكلي:</strong> {selectedActivity.totalFloat} يوم</div>
                            <div><strong>Float الحر:</strong> {selectedActivity.freeFloat} يوم</div>
                            <div className="col-span-2">
                                <strong>حرج:</strong> {selectedActivity.isCritical ? '★ نعم' : 'لا'}
                            </div>
                        </div>

                        {selectedActivity.sbcRequirements && selectedActivity.sbcRequirements.length > 0 && (
                            <div className="mt-4">
                                <h4 className="font-semibold mb-2">متطلبات الكود السعودي:</h4>
                                <div className="space-y-2">
                                    {selectedActivity.sbcRequirements.map((req, idx) => (
                                        <div key={idx} className={`p-2 rounded text-sm ${
                                            req.isCompliant 
                                                ? 'bg-green-50 dark:bg-green-900/20' 
                                                : 'bg-red-50 dark:bg-red-900/20'
                                        }`}>
                                            <p><strong>{req.code}:</strong> {req.description}</p>
                                            {req.minimumDuration && (
                                                <p className="text-xs mt-1">الحد الأدنى: {req.minimumDuration} يوم</p>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        <button
                            onClick={() => setSelectedActivity(null)}
                            className="mt-4 w-full bg-indigo-600 text-white py-2 rounded-lg hover:bg-indigo-700"
                        >
                            إغلاق
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
};

export default {
    SmartScheduleGenerator,
    AdvancedScheduleViewer
};
