"""Initial 14 tables - Complete NOUFAL database schema

Revision ID: 6570c26c87be
Revises: 
Create Date: 2025-12-09 05:54:14.124873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6570c26c87be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('consultant', sa.String(length=255), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('area', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('budget', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ar', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('LABOR', 'EQUIPMENT', 'MATERIAL', name='resourcetype'), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('availability', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('productivity_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('display_name_ar', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_ar', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('wbs_code', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('material_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('labor_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('equipment_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sbc_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_items_category'), 'boq_items', ['category'], unique=False)
    op.create_index(op.f('ix_boq_items_id'), 'boq_items', ['id'], unique=False)
    op.create_index(op.f('ix_boq_items_item_code'), 'boq_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_boq_items_project_id'), 'boq_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_boq_items_wbs_code'), 'boq_items', ['wbs_code'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('probability', sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='riskprobability'), nullable=False),
    sa.Column('impact', sa.Enum('VERY_LOW', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='riskimpact'), nullable=False),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('contingency_plan', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('IDENTIFIED', 'ASSESSING', 'MITIGATING', 'MONITORING', 'CLOSED', name='riskstatus'), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_category'), 'risks', ['category'], unique=False)
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_index(op.f('ix_risks_impact'), 'risks', ['impact'], unique=False)
    op.create_index(op.f('ix_risks_probability'), 'risks', ['probability'], unique=False)
    op.create_index(op.f('ix_risks_project_id'), 'risks', ['project_id'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_date', sa.Date(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_project_id'), 'schedules', ['project_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('boq_item_id', sa.Integer(), nullable=True),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('activity_name_ar', sa.String(length=255), nullable=True),
    sa.Column('wbs_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('actual_duration', sa.Integer(), nullable=True),
    sa.Column('early_start', sa.Date(), nullable=True),
    sa.Column('early_finish', sa.Date(), nullable=True),
    sa.Column('late_start', sa.Date(), nullable=True),
    sa.Column('late_finish', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('total_float', sa.Integer(), nullable=True),
    sa.Column('free_float', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('planned_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', 'CANCELLED', name='activitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_code'), 'activities', ['activity_code'], unique=False)
    op.create_index(op.f('ix_activities_boq_item_id'), 'activities', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_is_critical'), 'activities', ['is_critical'], unique=False)
    op.create_index(op.f('ix_activities_project_id'), 'activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_activities_schedule_id'), 'activities', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_activities_status'), 'activities', ['status'], unique=False)
    op.create_index(op.f('ix_activities_wbs_code'), 'activities', ['wbs_code'], unique=False)
    op.create_table('costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cost_type', sa.Enum('LABOR', 'MATERIAL', 'EQUIPMENT', 'SUBCONTRACTOR', 'OVERHEAD', 'OTHER', name='costtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costs_activity_id'), 'costs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_costs_cost_type'), 'costs', ['cost_type'], unique=False)
    op.create_index(op.f('ix_costs_date'), 'costs', ['date'], unique=False)
    op.create_index(op.f('ix_costs_id'), 'costs', ['id'], unique=False)
    op.create_index(op.f('ix_costs_invoice_number'), 'costs', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_costs_project_id'), 'costs', ['project_id'], unique=False)
    op.create_table('progress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('completed_quantity', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_logs_activity_id'), 'progress_logs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_progress_logs_date'), 'progress_logs', ['date'], unique=False)
    op.create_index(op.f('ix_progress_logs_id'), 'progress_logs', ['id'], unique=False)
    op.create_index(op.f('ix_progress_logs_project_id'), 'progress_logs', ['project_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('FS', 'SS', 'FF', 'SF', name='relationshiptype'), nullable=False),
    sa.Column('lag', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)
    op.create_index(op.f('ix_relationships_predecessor_id'), 'relationships', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_relationships_successor_id'), 'relationships', ['successor_id'], unique=False)
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_assignments_activity_id'), 'resource_assignments', ['activity_id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_id'), 'resource_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_resource_assignments_resource_id'), 'resource_assignments', ['resource_id'], unique=False)
    op.create_table('sbc_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('sbc_code', sa.String(length=50), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('is_compliant', sa.Boolean(), nullable=True),
    sa.Column('checked_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sbc_compliance_activity_id'), 'sbc_compliance', ['activity_id'], unique=False)
    op.create_index(op.f('ix_sbc_compliance_id'), 'sbc_compliance', ['id'], unique=False)
    op.create_index(op.f('ix_sbc_compliance_is_compliant'), 'sbc_compliance', ['is_compliant'], unique=False)
    op.create_index(op.f('ix_sbc_compliance_sbc_code'), 'sbc_compliance', ['sbc_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sbc_compliance_sbc_code'), table_name='sbc_compliance')
    op.drop_index(op.f('ix_sbc_compliance_is_compliant'), table_name='sbc_compliance')
    op.drop_index(op.f('ix_sbc_compliance_id'), table_name='sbc_compliance')
    op.drop_index(op.f('ix_sbc_compliance_activity_id'), table_name='sbc_compliance')
    op.drop_table('sbc_compliance')
    op.drop_index(op.f('ix_resource_assignments_resource_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_id'), table_name='resource_assignments')
    op.drop_index(op.f('ix_resource_assignments_activity_id'), table_name='resource_assignments')
    op.drop_table('resource_assignments')
    op.drop_index(op.f('ix_relationships_successor_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_predecessor_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_progress_logs_project_id'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_id'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_date'), table_name='progress_logs')
    op.drop_index(op.f('ix_progress_logs_activity_id'), table_name='progress_logs')
    op.drop_table('progress_logs')
    op.drop_index(op.f('ix_costs_project_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_invoice_number'), table_name='costs')
    op.drop_index(op.f('ix_costs_id'), table_name='costs')
    op.drop_index(op.f('ix_costs_date'), table_name='costs')
    op.drop_index(op.f('ix_costs_cost_type'), table_name='costs')
    op.drop_index(op.f('ix_costs_activity_id'), table_name='costs')
    op.drop_table('costs')
    op.drop_index(op.f('ix_activities_wbs_code'), table_name='activities')
    op.drop_index(op.f('ix_activities_status'), table_name='activities')
    op.drop_index(op.f('ix_activities_schedule_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_project_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_critical'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_boq_item_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_code'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_schedules_project_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_project_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_probability'), table_name='risks')
    op.drop_index(op.f('ix_risks_impact'), table_name='risks')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_category'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_boq_items_wbs_code'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_project_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_item_code'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_category'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
